### ISSUE TITLE
cd server && cnpm install && npm run dev

### ISSUE THREAD

**Issue by iouen** [DXY-F2E/api-mocker#35]
/home/app/api-mocker/server/node_modules/_egg-core@4.4.0@egg-core/lib/egg.js:239
    const closeFunction = async () => {
                                ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/app/api-mocker/server/node_modules/_egg-core@4.4.0@egg-core/index.js:3:17)
⚠️  Error: /home/app/api-mocker/server/node_modules/_egg-bin@4.3.7@egg-bin/lib/start-cluster {"baseDir":"/home/app/api-mocker/server","framework":"/home/app/api-mocker/server/node_modules/egg","workers":1} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail

**Comment by wuomzfx** [comment]
看一下node版本，小于 8.0 的话，升级到最新稳定版
