### ISSUE TITLE
cd server && cnpm install && npm run dev

### ISSUE THREAD

**Issue by jsondog** [DXY-F2E/api-mocker#43]
2018-11-21 15:51:30,743 ERROR 6868 nodejs.AppWorkerDiedError: [master] app_worker#2:6889 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["1","3","4"]
    at Master.onAppExit (/www/wwwroot/server.api.xxx.com/server/node_modules/egg-cluster/lib/master.js:398:21)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (/www/wwwroot/server.api.xxx.com/server/node_modules/egg-cluster/lib/utils/messenger.js:133:17)
    at Messenger.send (/www/wwwroot/server.api.xxx.com/server/node_modules/egg-cluster/lib/utils/messenger.js:98:12)
    at EventEmitter.cluster.on (/www/wwwroot/server.api.xxx.com/server/node_modules/egg-cluster/lib/master.js:267:22)
    at EventEmitter.emit (events.js:187:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AppWorkerDiedError"
pid: 6868
hostname: VM_161_185_centos

2018-11-21 15:51:30,745 ERROR 6868 [master] app_worker#2:6889 start fail, exiting with code:1
2018-11-21 15:51:30,745 ERROR 6868 [master] exit with code:1
2018-11-21 15:51:30,752 ERROR 6877 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110

[root@VM_161_185_centos server]# node -v
v10.13.0
[root@VM_161_185_centos server]# npm -v
6.4.1

**Comment by jsondog** [comment]
服务端一直安装不成功，不确定是nginx配置问题还是npm或者node版本问题

**Comment by pzljp** [comment]
@jsondog 请尝试一下更新node版本，清理一下npm缓存。看看现在是否能正常启动。

**Comment by pzljp** [comment]
欢迎加群反馈 
![image](https://user-images.githubusercontent.com/5746654/61603534-89386580-ac70-11e9-8dcb-2776c4d0b216.png)
