### ISSUE TITLE
server工程启动不了？npm ERR! server@1.3.1 dev: `egg-bin dev`

### ISSUE THREAD

**Issue by gaogaoyanjiu** [DXY-F2E/api-mocker#51]
#大神，这个错遇到过么
2019-06-13 17:05:55,906 ERROR 30841 [master] agent_worker#1:30849 start fail, exiting with code:1
2019-06-13 17:05:55,906 ERROR 30841 [master] exit with code:1
{ Error: /usr/local/api-mocker-dev/server/node_modules/egg-bin/lib/start-cluster {"workers":1,"baseDir":"/usr/local/api-mocker-dev/server","framework":"/usr/local/api-mocker-dev/server/node_modules/egg"} exit with code 1
    at ChildProcess.proc.once.code (/usr/local/api-mocker-dev/server/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.3.1 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.3.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-13T09_05_55_924Z-debug.log

**Comment by pzljp** [comment]
有没有按照要求复制core.js和manager.js?可以加微信568928535，远程支持你启动。

**Comment by pzljp** [comment]
欢迎加群反馈 ![image](https://user-images.githubusercontent.com/5746654/61603490-51c9b900-ac70-11e9-9054-34af81448ec1.png)
